gemma2_2b_base:
  prompt_template: 
  fn_completions: 'huggingface_local_completions'
  completions_kwargs:
    model_name: 'gemma2_2b_base'
    batch_size: 16
    model_kwargs:
      torch_dtype: 'bfloat16'
      attn_implementation: 'eager'
    max_new_tokens: 2048
    temperature: 0.9
    top_p: 1.0
    do_sample: True
  pretty_name: 'gemma2_2b_base'
  link: 'https://huggingface.co/google/gemma-2-2b'