llama2_13b_base:
  prompt_template:
  fn_completions: 'vllm_local_completions'
  completions_kwargs:
    model_name: 'llama2_13b_base'
    batch_size: 900
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.9
    top_p: 1.0
    do_sample: True
  pretty_name: 'llama2_13b_base'
  link: 'https://huggingface.co/meta-llama/Llama-2-13b-hf'

  
