mistral_7b_v0.2_base:
  prompt_template:
  fn_completions: 'vllm_local_completions'
  completions_kwargs:
    model_name: 'mistral_7b_v0.2_base'
    batch_size: 900
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.9
    top_p: 1.0
    do_sample: True
  pretty_name: 'mistral_7b_v0.2_base'
  link: 'https://huggingface.co/mistral-community/Mistral-7B-v0.2'

  
