default:
    - api_key: "[OPENAI_API_KEY]"
    
gpt-4-1106-preview: # only when using `model_name: gpt-4-1106-preview` which is AlpacaEval2's model name
    - "default" # use default `openai.OpenAI` client
    # - client_class: "openai.AzureOpenAI" # alternatively decomment the next five lines to use the `openai.AzureOpenAI` client
    #   azure_deployment: "gpt-4-1106-preview"
    #   api_key: "[AZURE_OPENAI_API_KEY]"
    #   azure_endpoint: "[AZURE_OPENAI_ENDPOINT]"
    #   api_version: "[OPENAI_API_VERSION]"